spring:
  thymeleaf:
    cache: false
  jmx:
    enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dragondb?serverTimezone=Asia/Tokyo
    username: root
    password: mysql

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapper-locations:
    - classpath*:/jp/co/internous/dragon/model/mapper/**/*.xml

logging:
  level:
    org:
      springframework: WARN
    jp:
      co:
        internous:
          dragon:
            model:
              mapper: DEBUG
